name 'jboss'
depends 'java'
maintainer 'Uladzislau_Charches'
maintainer_email 'Uladzislau_Charches@epam.com'
license 'GNU'
description 'Installation & Configuration Jboss'
long_description 'Installation & Configuration Jboss'
version '0.1.0'
